- name: TOwer with github
  hosts: all
  tasks:
     - name: create file 
       copy:
            content: "Hello GIthub"
            dest: /tmp/abc.txt


     - yum:
            name: ftp
            state: installed

